# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SSFloatingTextFieldDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'SSFloatingLabelTextField', :git => "https://github.com/mobile-simformsolutions/SSFloatingLabelTextField", :branch => "feature/createpod"

# Pods for SSFloatingTextFieldDemo

end
